export const scanTableData = [
  {
    id: "scan-1",
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    vulnerabilities: {
      critical: 5,
      high: 12,
      medium: 23,
      low: 18,
    },
    lastScan: "4d ago",
  },
  {
    id: "scan-2",
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    vulnerabilities: {
      critical: 5,
      high: 12,
      medium: 23,
      low: 18,
    },
    lastScan: "4d ago",
  },
  {
    id: "scan-3",
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    vulnerabilities: {
      critical: 5,
      high: 12,
      medium: 23,
      low: 18,
    },
    lastScan: "4d ago",
  },
  {
    id: "scan-4",
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    vulnerabilities: {
      critical: 5,
      high: 12,
      medium: 23,
      low: 18,
    },
    lastScan: "4d ago",
  },
  {
    id: "scan-5",
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    vulnerabilities: {
      critical: 5,
      high: 12,
      medium: 23,
      low: 18,
    },
    lastScan: "4d ago",
  },
  {
    id: "scan-6",
    name: "Web App Servers",
    type: "Greybox",
    status: "Scheduled",
    progress: 100,
    vulnerabilities: {
      critical: 5,
      high: 12,
      medium: 0,
      low: 0,
    },
    lastScan: "4d ago",
  },
  {
    id: "scan-7",
    name: "Web App Servers",
    type: "Greybox",
    status: "Scheduled",
    progress: 100,
    vulnerabilities: {
      critical: 5,
      high: 12,
      medium: 0,
      low: 0,
    },
    lastScan: "4d ago",
  },
  {
    id: "scan-8",
    name: "IoT Devices",
    type: "Blackbox",
    status: "Failed",
    progress: 10,
    vulnerabilities: {
      critical: 2,
      high: 4,
      medium: 8,
      low: 1,
    },
    lastScan: "3d ago",
  },
  {
    id: "scan-9",
    name: "Temp Data",
    type: "Blackbox",
    status: "Failed",
    progress: 10,
    vulnerabilities: {
      critical: 2,
      high: 4,
      medium: 8,
      low: 1,
    },
    lastScan: "3d ago",
  },
]